#!/bin/bash

set -e

echo "To use this script, execute it like this: eval \$(aws-session)" >&2

which aws >/dev/null || { echo "Required but not installed: aws" >&2; exit 1; }
which jq >/dev/null || { echo "Required but not installed: jq" >&2; exit 1; }

mfa_devices=$(aws iam list-mfa-devices)
mfa_device=$(echo "${mfa_devices}" | jq -r '.MFADevices[0].SerialNumber')
echo "Found MFA device: ${mfa_device}" >&2

read -p "Please input MFA token code: " token_code >&2

aws_session=$(aws sts get-session-token --serial-number "${mfa_device}" --token-code "${token_code}")
aws_key=$(echo "${aws_session}" | jq -r '.Credentials.AccessKeyId')
aws_secret=$(echo "${aws_session}" | jq -r '.Credentials.SecretAccessKey')
aws_token=$(echo "${aws_session}" | jq -r '.Credentials.SessionToken')
echo "Temporary access key: ${aws_key} (secret: redacted token: redacted)" >&2

echo "export AWS_ACCESS_KEY_ID=\"${aws_key}\""
echo "export AWS_SECRET_ACCESS_KEY=\"${aws_secret}\""
echo "export AWS_SESSION_TOKEN=\"${aws_token}\""
